[project]
name = 'Blockchain-Based-Manufacturing-Energy-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consumption-baseline]
path = 'contracts/consumption-baseline.clar'
clarity_version = 2
epoch = 2.5

[contracts.efficiency-project]
path = 'contracts/efficiency-project.clar'
clarity_version = 2
epoch = 2.5

[contracts.facility-verification]
path = 'contracts/facility-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.savings-verification]
path = 'contracts/savings-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
